### ISSUE TITLE
Excepted output of the example 

### ISSUE THREAD

**Issue by Anton-Prab** [lemmingapex/trilateration#12]
I've managed to execute the example that you've given in the Readme section. But Im not able to understand the output that ive got. Please make me clear on this. I've posted a [question ](https://stackoverflow.com/questions/44113563/2d-trilateration-using-trilateration-application)about this in stackoverflow. Hope you could give me a right solution there. I dont know how to reach you thats why ive raised as a issue here.

**Comment by lemmingapex** [comment]
I will address your question on stackoverflow.  Please PM me in the future.
