### ISSUE TITLE
How do i get coordinate of esclipe's point

### ISSUE THREAD

**Issue by vitrinh282** [lemmingapex/trilateration#17]
where do i get coordinate (x,y) from output?

**Comment by lemmingapex** [comment]
Did you look at the README and/or the tests?

**Comment by vitrinh282** [comment]
yes , but i'm still not clear, could you explain me how to get it?

**Comment by lemmingapex** [comment]
// the answer
double[] centroid = optimum.getPoint().toArray();

System.out.println("x: " + centroid[0]);
System.out.println("y: " + centroid[1]);

**Comment by quangvi282** [comment]
thks but could you tell me about beacons? how many percents is right ?
