### ISSUE TITLE
SingularMatrixException on Error Calculation

### ISSUE THREAD

**Issue by bleckers** [lemmingapex/trilateration#2]
Hi Scott,

It seems the following two lines both give a SingularMatrixException when run:

// error and geometry information
RealVector standardDeviation = optimum.getSigma(0);
RealMatrix covarianceMatrix = optimum.getCovariances(0);

I cannot get it to work with any input data. For example, here are some positions that throw the error (these are a Mercator projection of GPS coordinates):
Positions[0]:
0 = -4565919.193832541
1 = 1.6141672528603023E7
2 = 2200.0

Positions[1]:
0 = -4565920.313515583
1 = 1.6141679993156526E7
2 = 2200.0

Positions[2]:
0 = -4565927.778069112
1 = 1.6141678948119089E7
2 = 2200.0

Positions[3]:
0 = -4565926.658386086
1 = 1.6141671334274463E7
2 = 2200.0

Distances:
0 = 1.6
1 = 1.6
2 = 1.6
3 = 1.6

Would you have any idea as to why this might be the case? This is running on Android with the same (recently updated) Apache commons Math3 library you are using. It also doesn't work with the previous version of the library.

Calculating the point estimate works perfectly fine.

Regards,

Blair

**Comment by bleckers** [comment]
Aha! 

It seems to only happen when using a third position (altitude) in the Positions array. When you remove this it calculates both of these just fine.

Creating a separate function to calculate the error with only a two element position (lat/lng) allows you to calculate this just fine.

**Comment by lemmingapex** [comment]
Hi Blair,

I have seen this exception before when requesting the error information.  It likely means that this information is meaningless.

When you request sigma, the covariance of the Jacobian matrix is determined in a [QRDecomposition](https://en.wikipedia.org/wiki/QR_decomposition).  The _double threshold_ argument you provide to getSigma is a way for the caller to specify that the result of this computation should be considered meaningless, and thus trigger an exception.  In your above example, change _optimum.getSigma(0);_ and _optimum.getCovariances(0);_ to _optimum.getSigma(-1);_ and _optimum.getCovariances(-1);_ respectively.  This will likely cause you to obtain NaN entries in your results.  Meaningless, right?

Do you think if the above information was better documented, this would avoid confusion in the future?  What do you think?

Thanks,
Scott

**Comment by bleckers** [comment]
I think a brief explanation in the readme on the threshold value and an example on how to handle a meaningless result/exception should suffice. It just threw me because the optimum was calculated just fine.

**Comment by lemmingapex** [comment]
@bleckers, I put a short comment in the [README](../blob/master/README.md).  Take a look, let me know what you think.  Can I close this issue?

**Comment by bleckers** [comment]
Maybe something about what input variables might constitute a SingularMatrixException? Most people will be using this library without going into detail about the maths involved and it would be useful to know when they might experience the error (like for example above when using a 3D coordinate space).

**Comment by wsingh23** [comment]
Anyone can tell me how to run this code with proper snapshot so that I can run this code and see the results. It will be very helpful if someone give me the idea to run this code

**Comment by bleckers** [comment]
Hi wsingh23,

The test code (https://github.com/lemmingapex/Trilateration/blob/master/src/test/java/com/lemmingapex/trilateration/TrilaterationTest.java) gives a examples of how to use the code.

Take a look at that as a starting point.

**Comment by lemmingapex** [comment]
Everything related to SingularMatrixException is well documented in apache's docs:
https://commons.apache.org/proper/commons-math/apidocs/org/apache/commons/math3/fitting/leastsquares/LeastSquaresProblem.Evaluation.html#getSigma(double)

Users looking to find out more about how these methods should look there.

**Comment by wsingh23** [comment]
how to run this code i mean to say on which platform i have to run this
code java android or any other platform please explain  me step by step.

**Comment by rosivivas** [comment]
Hi 
This library works with android screen coordinate system?

I have four beacons and I need draw user position, but always return same position regardless of which beacon is closest to the user
