### ISSUE TITLE
How to determine the accuracy of the coordinate

### ISSUE THREAD

**Issue by alettazz** [lemmingapex/trilateration#22]
As this gives an optimized centroid I would be interested in any suitable idea on how to determine  the accuracy of the result coordinate in case i can provide the real coordinates.
As for testing the correctness of the algorithm, given the fix coordinate comparing with the centroid coordinate, what's the best way to predict the accuracy?
@lemmingapex

**Comment by kburfi** [comment]
You can simply use the euclidean distance. You are just calculating the distance between two points in an n-dimensional space.
