### ISSUE TITLE
Distance between coordinates

### ISSUE THREAD

**Issue by MoeBro** [lemmingapex/trilateration#23]
Hi. 
I was looking to use your library for trilateration with BLE beacons. I can get the distances from the beacons however there was a thing i am wondering about. 
How do you know what the distances are between the different points in the coordinate system? 
Lets say for example the distance between the point (0,-1) and (0,-2)

**Comment by kburfi** [comment]
The distance between points is the euclidean distance

**Comment by MoeBro** [comment]
Lets say i have a room that is 20m x 20m. If i place a beacon in each corner of the room and set their coordinates as such. Then if i stand in the middle of the room should i then get the location of (10,-10)? 
Like this: 
![location](https://user-images.githubusercontent.com/17564724/55233461-0440c080-5229-11e9-880c-8ac2bc96d065.png)

**Comment by kburfi** [comment]
Yes that is true - but do you have an actual question regarding this library?

**Comment by MoeBro** [comment]
No, its all good, i know what i need :) 
Do you recommend using Kalman or Particle filter to get more accuracy btw?

**Comment by lemmingapex** [comment]
Both of these types filters are very application specific.  This topic is outside the scope of this library.
