### ISSUE TITLE
Beacon coordinates

### ISSUE THREAD

**Issue by MoeBro** [lemmingapex/trilateration#24]
When i assign coordinates to my beacons, how do i know which beacon is assigned to which coordinate?

**Comment by lemmingapex** [comment]
Beacons?  This question has nothing to do with this library.

**Comment by MoeBro** [comment]
What are the positions for then? 
in this: 
![image](https://user-images.githubusercontent.com/17564724/55492664-e1067e80-5637-11e9-80b2-a4fd7cc296eb.png)
