### ISSUE TITLE
What are the positions for?

### ISSUE THREAD

**Issue by MoeBro** [lemmingapex/trilateration#25]
I should have clarified, im using your library along with my own BLE beacons, to use trilateration in order to track my location. 
If i want to place my beacons inside a room, using the coordinates, how do i know which coordinate belongs to which beacon im using?
in this: 
![image](https://user-images.githubusercontent.com/17564724/55493341-0b0c7080-5639-11e9-82e4-03d123f4ed87.png)

**Comment by kburfi** [comment]
The positions and distances you copied are an example for input parameters.
The example has 4 Positions with x and y components: e.g. {5.0, -6.0} means x=5; y=-6
The distances are the measured distances to each position. This means that both arrays correspond in length in their first dimension.

**Comment by MoeBro** [comment]
So if i want to use BLE beacons inside a room and find my own location, how could i use the library for that?

**Comment by kburfi** [comment]
Please keep in mind that this is an issue tracker, not maths class. As you don't seem to have an issue with this library I'm going to close the thread.
