### ISSUE TITLE
Incompatibles type LevenbergMarquardtOptimizer cannot be converted to LeastSquaresOptimizer 	NonLinearLeastSquaresSolver

### ISSUE THREAD

**Issue by benjaminpeere** [lemmingapex/trilateration#28]
Hello, 
I am trying to implement your solution, but I am having a problem, here is the error that I have : 
```
incompatible types: LevenbergMarquardtOptimizer cannot be converted to LeastSquaresOptimizer
	NonLinearLeastSquaresSolver solver = new NonLinearLeastSquaresSolver(new TrilaterationFunction(positions, distances), new LevenbergMarquardtOptimizer());
```
I really don't know why I am having this error, if I am doing something wrong, or if there is a type problem in the plugin.
Let me know if you have any idea.

Thanks for your work, if I can make it work it would be amazing!
Best regards.

**Comment by kburfi** [comment]
I think you may have imported a wrong or deprecated version of LevenbergMarquardtOptimizer.
The correct import is:
`import org.apache.commons.math3.fitting.leastsquares.LevenbergMarquardtOptimizer;`

**Comment by benjaminpeere** [comment]
You're right! I wa susing a the wrong import, thank you so much!
