### ISSUE TITLE
How to use it in R³ localization?

### ISSUE THREAD

**Issue by ppooii12009** [lemmingapex/trilateration#30]
I want to do some localizations in real spaces through iBeacon devices, and have successfully imported your dependency.
But the sample codes only show how to reach the answer in R² space 
so how to use it in R³ space ?

**Comment by kburfi** [comment]
The double[][] positions in the example is n-dimensional.
In the second dimension of the array you can give the n-dimensional Positions, e. g.
double[][] positions = new double[][] { { 5.0, -6.0, 6.5 }, { 13.0, -15.0, -2.3 }, { 21.0, -3.0, -4.6 }, { 12.4, -21.2, -7,3 } };

**Comment by ppooii12009** [comment]
Got it ! I just misunderstood the meaning of array 'positions'
Great gratitude !
